import { GoogleGenAI, Type } from "@google/genai";
import { TagResult } from "../types";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

/**
 * Generates SEO tags using Gemini 2.5 Flash.
 */
export const generateTags = async (keyword: string): Promise<TagResult[]> => {
  if (!apiKey) throw new Error("API Key not found");

  const prompt = `
    Generate 5 to 10 highly searchable, trending, and short-value tags for the keyword: "${keyword}".
    Consider current trends on Google and YouTube.
    Return the response as a JSON array where each object has:
    - tags: array of strings (the hashtags)
    - trendingScore: number (0-100)
    - searchVolume: string (e.g., "High", "Medium", "Very High")
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              tags: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
              },
              trendingScore: { type: Type.NUMBER },
              searchVolume: { type: Type.STRING },
            },
          },
        },
      },
    });

    const text = response.text;
    if (!text) return [];
    return JSON.parse(text) as TagResult[];
  } catch (error) {
    console.error("Gemini Tag Error:", error);
    throw error;
  }
};

/**
 * Edits an image using Gemini 2.5 Flash Image.
 */
export const editImage = async (base64Image: string, prompt: string): Promise<string> => {
  if (!apiKey) throw new Error("API Key not found");

  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: cleanBase64,
            },
          },
          {
            text: `Edit this image: ${prompt}. Maintain the main subject. High quality, photorealistic.`,
          },
        ],
      },
    });

    for (const candidate of response.candidates || []) {
      for (const part of candidate.content?.parts || []) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};

/**
 * Enhances/Upscales an image using Gemini 2.5 Flash Image.
 */
export const enhanceImage = async (base64Image: string): Promise<string> => {
  if (!apiKey) throw new Error("API Key not found");

  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  const enhancementPrompt = "Upscale this image to high resolution (4K). Remove noise, sharpen details, improve lighting and contrast, and make it look professional and photorealistic. Maintain the original subject and composition exactly, just improve quality.";

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: cleanBase64,
            },
          },
          {
            text: enhancementPrompt,
          },
        ],
      },
    });

    for (const candidate of response.candidates || []) {
      for (const part of candidate.content?.parts || []) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini Image Enhance Error:", error);
    throw error;
  }
};
